name: Validate Jira ticket link

on:
  pull_request:
     types: [opened, edited]

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  read-pr-title:
    runs-on: ubuntu-latest
    steps: 
      - name: Append PR link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{github.event.pull_request.title}}
          PR_BODY: ${{github.event.pull_request.body}}
          PR_NUMBER: ${{github.event.pull_request.number}}
          REPO: ${{github.repository}}
          JIRA_LINK: "https://apexclearing.atlassian.net/browse"
        run: |
          TICKETS=$(echo "$PR_TITLE" | grep -oE '[A-Z]+-[0-9]+' | sort | uniq) || true
          if [[ -z "$TICKETS" ]]; then
            echo "Ticket Number not present in PR title."
            echo "$TICKET"
            exit 0
          fi

          MISSING_LINKS=()
          for TICKET in $TICKETS; do
            TICKET_LINK="[$TICKET]($JIRA_LINK/$TICKET)"
            FULL_LINK="Link to Ticket: $TICKET_LINK"
            if ! echo "$PR_BODY" | grep -q -F "$FULL_LINK"; then
              MISSING_LINKS+=("$FULL_LINK")
            fi
          done

          if [[ ${#MISSING_LINKS[@]} -eq 0 ]]; then
            echo "All tickets already linked in PR description."
            exit 0
          fi

          LINKS_BLOCK=$(printf '%s\n' "${MISSING_LINKS[@]}")

          NEW_BODY="$LINKS_BLOCK

          $PR_BODY"
          
          API_URL="https://api.github.com/repos/$REPO/pulls/$PR_NUMBER"
          PAYLOAD=$(jq --null-input --arg body "$NEW_BODY" '{body: $body}')

          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$PAYLOAD" "$API_URL"
          echo "Appended JIRA link to PR description."
  
    

  


