name: Validate Jira ticket link

on:
  pull_request:
     types: [opened, edited]

jobs:
  read-pr-title:
    runs-on: ubuntu-latest
    steps: 
      - name: Append PR link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{github.event.pull_request.title}}
          PR_BODY: ${{github.event.pull_request.body}}
          PR_NUMBER: ${{github.event.pull_request.number}}
          REPO: ${{github.repository}}
        run: |
          TICKET=$(echo "$PR_TITLE" | grep -oE '^[A-Z]+-[0-9]+')
          if [[ -z "$TICKET" ]]; then
            echo "Ticket Number not present in PR title."
            exit 0
          fi

          JIRA_LINK="https://apexclearing.atlassian.net/browse/$TICKET"
          if echo "$PR_BODY" | grep -q "$JIRA_LINK"; then
            echo "Ticket '$TICKET' already found in PR description."
            exit 0
          fi

          NEW_BODY="$PR_BODY
          
          Link to ticket: $JIRA_LINK"
          
          API_URL="https://api.github.com/repos/$REPO/pulls/$PR_NUMBER"
          PAYLOAD=$(jq --null-input --arg body "$NEW_BODY" '{body: $body}')

          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "$PAYLOAD" "$API_URL"
          echo "Appended JIRA link to PR description."
  
    

  


